version: "3"
services:

  db:
    image: "postgres"
    container_name: "my_db"
    environment:
      - POSTGRES_USER=alismed
      - POSTGRES_PASSWORD=0123456789
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: "my_pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "myemail@yahoo.com"
      PGADMIN_DEFAULT_PASSWORD: "Pass001!"
    ports:
      - "16543:80"
    depends_on:
      - db

