source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'rails-api'
gem 'mysql2'
gem 'puma'

# Use ActiveModelSerializers to serialize JSON responses
gem 'active_model_serializers', '~> 0.10.0.rc3'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
group :development do 
  gem 'spring'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Deploy with Capistrano
# gem 'capistrano', :group => :development


